networks:
  app_net_automation_backups:
    external: false

services:
  
  db:
    container_name: db_automation_backups
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5433:5432
    volumes:
      - db:/db/postgres/db_automation
    networks:
      app_net_automation_backups:
        aliases:
          - app_automation

volumes:
  db: